export const resturant = [
    {   id: 1,
        name : "Punjab Grill",
        category : "North India. Fast food",
        location : "Khorda, Bhubneswar",
        distance : "3.7km",
        offer : "20%",
        image : "/images/resturant1.jpg"
    },
    {   id: 2,
        name : "Biriyani Box",
        category : "South India",
        location : "Rasulgrah, Bhubneswar",
        distance : "6.9km",
        offer : "10%",
        image : "/images/resturant2.jpg"
    },
    {   id: 3,
        name : "Svadu Resturant",
        category : "Chinese.North India",
        location : "Kharbel Nagar, Bhubneswar",
        distance : "9km",
        offer : "17%",
        image : "/images/resturant3.jpg"
    },
    {   id: 4,
        name : "Bocca Cafe",
        category : "Beverages.Desserts",
        location : "Patia, Bhubneswar",
        distance : "14km",
        offer : "10%",
        image : "/images/resturant4.jpg"
    },
    {   id: 5,
        name : "Punjab Grill",
        category : "North India. Fast food",
        location : "Khorda, Bhubneswar",
        distance : "3.7km",
        offer : "20%",
        image : "/images/resturant5.jpg"
    },
    {   id: 6,
        name : "Biriyani Box",
        category : "South India",
        location : "Rasulgrah, Bhubneswar",
        distance : "6.9km",
        offer : "10%",
        image : "/images/resturant6.jpg"
    },
    {   id: 7,
        name : "Svadu Resturant",
        category : "Chinese.North India",
        location : "Kharbel Nagar, Bhubneswar",
        distance : "9km",
        offer : "17%",
        image : "/images/resturant7.jpg"
    },
    {   id: 8,
        name : "Bocca Cafe",
        category : "Beverages.Desserts",
        location : "Patia, Bhubneswar",
        distance : "14km",
        offer : "10%",
        image : "/images/resturant8.jpg"
    }
]